<?php

// Import file as an array per newline

function import_data($filename)
{
    if (filesize($filename) == 0)
    {
        return FALSE;
    }
    else
    {
    $handle = fopen($filename, "r");
    $contents = fread($handle, filesize($filename));
    $content_array = explode("\n", $contents);
    fclose($handle);
    return $content_array;
    }
}

// create multidimensional array of entries by tab

function explode_entries($array)
{
	$new_array = [];

	foreach($array as $entry)
	{
		$new_array[] = explode("\t", $entry);

	}

	return $new_array;
}

// returns an array of five rolls of a six-sided die

function roll_five()
{
	$roll_array = [];
	for($i=1; $i<=5; $i++)
	{
		$roll_array[] = mt_rand(1,6);
	}
	return $roll_array;

}

// returns an array of strings, each a 5-digit number generated by the dice

function get_rolls($int)
{
	$dice_array = [];

	for($i = 0; $i < $int; $i++)
	{
		$dice_array[] = implode('', roll_five());
	}
	return $dice_array;
}

// get user input

function get_input($upper = FALSE)
{
    
    $user_input = trim(fgets(STDIN));
    return $upper ? strtoupper($user_input) : $user_input;

}

// Convert the random numbers into diceware words

function generate_words($array, $diceware)
{
	$dice_words = [];

	foreach($array as $value)
	{
		foreach($diceware as $entry)
		{
			if (intval($value) == intval($entry[0]))
			{
				$dice_words[] = $entry[1];
				break;
			}
		}
	}
	return $dice_words;
}

// initialize diceware file key

$diceware_array = import_data("../data/diceware.txt");
$diceware_multi = explode_entries($diceware_array);

// var_dump($diceware_multi);
// var_dump($diceware_array);

fwrite(STDIN, PHP_EOL . "How many words do you want to use to create your passphrase?" .
	PHP_EOL . "(5) is the default: ");

$num_dice = intval(get_input());

// set default number of passphrase words to 5.

if (!$num_dice)
{
	$num_dice = 5;
}

$dice_numbers = get_rolls($num_dice);
$pass_words = generate_words($dice_numbers, $diceware_multi);

// var_dump($pass_words);

fwrite(STDIN, PHP_EOL . "Your pass phrase words are: " . PHP_EOL . implode("\n", $pass_words) . PHP_EOL);

//var_dump($dice_numbers);
// var_dump(implode('', roll_five()));

?>